Add typing check to GitHub CI workflows

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -216,7 +216,7 @@ jobs:
             torch torchvision
           python -m pip install datasets scipy tokenizers transformers
           # Testing dependencies.
-          python -m pip install 'pytest>=8.2' pytest-cov pytest-dirty
+          python -m pip install mypy 'pytest>=8.2' pytest-cov pytest-dirty
       - name: Run dirty tests with PyTest
         if: 'github.event.pull_request'
         run: |
@@ -243,3 +243,7 @@ jobs:
           path: |
             coverage
             pytest
+      # This step never fails but it is useful to monitor status of type
+      # corectness.
+      - name: Check typing
+        run: mypy wrappers/python/nntile || true
